CREATE TABLE users (
    id         VARCHAR(128) NOT NULL PRIMARY KEY,
    email      VARCHAR(254) NOT NULL,
    created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME,

    INDEX idx_users_email(email)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4;
